import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Viewly</title>
       <link rel="icon" href="/logo-viewly.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Offside&family=SUSE+Mono:ital,wght@0,100..800;1,100..800&display=swap"
          rel="stylesheet"
        ></link>
        <meta property="og:title" content="Viewly"/>
        <meta property="og:description" content="Rate The Movie You Watched Today"/>
        <meta property="og:url" content="https://viewly-two.vercel.app/"/>
        <meta property="og:image" content="https://viewly-two.vercel.app/logo-viewly.png"/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
